### ISSUE TITLE
Application Form technical debt (using for tracking, can work on after v1 launch)

### ISSUE THREAD

**Issue by kailanjian** [International-Mentorship-ISMP/ismp#122]
ApplicationForm.jsx:
- [ ] Split out application form specific validation logic into ApplicationForm specific validator class
- [ ] Split out generic validation logic into helper file that can be used across app (maybe not worth doing, depending on what other forms we need)
- [ ] Implement visual tests for each page
- [ ] Test validation logic
- [ ] Test debug flag (potentially move out the debug flag or read from environment variable)
- [ ] Move out state logic (not sure how much this makes sense, low priority)
- [ ] Separate special cases in submit logic for date parsing and checkbox parsing
- [ ] Decouple submit logic from input
- [ ] https://github.com/International-Mentorship-ISMP/ismp/pull/171#discussion_r439778549
- [ ] DRY out Terms modal and Privacy Policy Modal
