### ISSUE TITLE
Pilot image loading from S3 depending on the environment

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#264]
**Description**
[Decision Thread](https://3.basecamp.com/4474129/buckets/16925967/messages/2774323209#__recording_2777877082)

Change our image loading to be:

1. Keep images on S3
2. Have different S3 buckets for environments, we already have this.
3. S3 file structure between different envs will be consistent. The only thing that changes is the base bucket name and that will be passed in locally, any cloud environment via an environment variable.
	4. Django already looks for this.

- [x] I've added the proper component `comp/*` label + other labels
- [x] I've added any context to where the decision was made (Basecamp links...etc.)

# Todos
- [x] Quick local test to read env vars on client side properly
- [ ] Add new S3 bucket https://github.com/International-Mentorship-ISMP/ismp/issues/267
- [ ] Test out image loading from existing buckets. Confirm what S3 settings we need.
- [ ] Setup utils for S3 loading on client side code
- [ ] Make followup issues for migrating image loading to s3
- [ ] Make followup task or do spike for `localstack` development with an image setup to run locally with our static S3 data.

**Comment by JonSEng** [comment]
See https://github.com/International-Mentorship-ISMP/ismp/pull/265 for an example of how this was shown to work locally.
